package envwriter

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// Writer writes secret key/value pairs to a .env file.
type Writer struct {
	outputPath string
}

// NewWriter creates a Writer that targets the given file path.
func NewWriter(outputPath string) *Writer {
	return &Writer{outputPath: outputPath}
}

// Write serialises the provided secrets map into the .env file,
// overwriting any existing content. Keys are written in sorted order
// for deterministic output.
func (w *Writer) Write(secrets map[string]string) error {
	if len(secrets) == 0 {
		return fmt.Errorf("no secrets provided to write")
	}

	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by vaultpipe — do not edit manually\n")
	for _, k := range keys {
		v := secrets[k]
		// Quote values that contain spaces or special characters.
		if strings.ContainsAny(v, " \t\n#") {
			v = fmt.Sprintf(`"%s"`, strings.ReplaceAll(v, `"`, `\"`))
		}
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, v))
	}

	//nolint:gosec // .env files are intentionally world-readable in dev
	if err := os.WriteFile(w.outputPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing env file %q: %w", w.outputPath, err)
	}
	return nil
}
