package envwriter

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func tempEnvFile(t *testing.T) string {
	t.Helper()
	return filepath.Join(t.TempDir(), ".env")
}

func TestWrite_CreatesFile(t *testing.T) {
	path := tempEnvFile(t)
	w := NewWriter(path)

	err := w.Write(map[string]string{"FOO": "bar"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Fatal("expected file to be created")
	}
}

func TestWrite_ContentsCorrect(t *testing.T) {
	path := tempEnvFile(t)
	w := NewWriter(path)

	secrets := map[string]string{"DB_HOST": "localhost", "DB_PORT": "5432"}
	if err := w.Write(secrets); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading file: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "DB_HOST=localhost") {
		t.Errorf("expected DB_HOST=localhost in output")
	}
	if !strings.Contains(content, "DB_PORT=5432") {
		t.Errorf("expected DB_PORT=5432 in output")
	}
	if !strings.HasPrefix(content, "# Generated by vaultpipe") {
		t.Errorf("expected header comment at top of file")
	}
}

func TestWrite_QuotesValuesWithSpaces(t *testing.T) {
	path := tempEnvFile(t)
	w := NewWriter(path)

	if err := w.Write(map[string]string{"MSG": "hello world"}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, _ := os.ReadFile(path)
	if !strings.Contains(string(data), `MSG="hello world"`) {
		t.Errorf("expected value with spaces to be quoted, got:\n%s", string(data))
	}
}

func TestWrite_EmptySecretsReturnsError(t *testing.T) {
	path := tempEnvFile(t)
	w := NewWriter(path)

	err := w.Write(map[string]string{})
	if err == nil {
		t.Fatal("expected error for empty secrets map, got nil")
	}
}

func TestWrite_SortedOutput(t *testing.T) {
	path := tempEnvFile(t)
	w := NewWriter(path)

	if err := w.Write(map[string]string{"Z_KEY": "z", "A_KEY": "a", "M_KEY": "m"}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, _ := os.ReadFile(path)
	content := string(data)
	idxA := strings.Index(content, "A_KEY")
	idxM := strings.Index(content, "M_KEY")
	idxZ := strings.Index(content, "Z_KEY")
	if !(idxA < idxM && idxM < idxZ) {
		t.Errorf("expected keys in sorted order, got:\n%s", content)
	}
}

func TestWrite_OverwritesExistingFile(t *testing.T) {
	path := tempEnvFile(t)
	w := NewWriter(path)

	// Write initial content
	if err := w.Write(map[string]string{"OLD_KEY": "old_value"}); err != nil {
		t.Fatalf("unexpected error on first write: %v", err)
	}

	// Overwrite with new content
	if err := w.Write(map[string]string{"NEW_KEY": "new_value"}); err != nil {
		t.Fatalf("unexpected error on second write: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading file: %v", err)
	}
	content := string(data)

	if strings.Contains(content, "OLD_KEY") {
		t.Errorf("expected OLD_KEY to be gone after overwrite, got:\n%s", content)
	}
	if !strings.Contains(content, "NEW_KEY=new_value") {
		t.Errorf("expected NEW_KEY=new_value in output, got:\n%s", content)
	}
}
